Feature/plan api v0.2
Nexters/travel-budget-server pull request #17
Opened 2020-07-30 17:29 UTC by giyeon95

2020-07-31 23:41 UTC, godong9 commented on src/main/java/com/strictmanager/travelbudget/domain/budget/BudgetService.java
> +    // TODO: PlanId를 받아와서, budget을 가져오는데,
일단 그냥 여기 두시죠~

2020-07-31 23:45 UTC, godong9 commented on src/main/java/com/strictmanager/travelbudget/web/AuthController.java
> +    public static class KakaoUserRequest {
이거 public 으로 바꾼 이유가 있나요?
Controller 내부에서만 쓰려고 일부러 private 으로 한건데...

2020-07-31 23:48 UTC, godong9 commented on src/main/java/com/strictmanager/travelbudget/web/PlanController.java
> +        Budget budget;
이 밑에도 Manager 로 옮겨야할거 같아요~
PlanDetailManager 같은걸로

2020-07-31 23:50 UTC, godong9 requested changes
리뷰 의견 남겼습니다. 
나머진 좋은것 같아요!! 👍

2020-08-01 02:42 UTC, giyeon95 commented on src/main/java/com/strictmanager/travelbudget/web/AuthController.java
> +    public static class KakaoUserRequest {
테스트 케이스 해본다고 임시로 바꿨다가
커밋이 함께 되었나보네요 ㅠㅠ.. 저거는 다시 수정하도록 할께요

2020-08-01 02:44 UTC, giyeon95 commented on src/main/java/com/strictmanager/travelbudget/web/PlanController.java
> +        Budget budget;
기능구현하고 분리한다는게, 그대로 두었네요 ㅎㅎ.. 분리하도록 할께요~~

2020-08-01 04:46 UTC, godong9 approved these changes
리뷰 내용만 반영되면 머지하면 될거같아요~
고생많으셨습니다 👍

2020-08-01 09:31 UTC, merged